### ISSUE TITLE
Move documentation to ros2 documentation (already removed references to ros wiki)

### ISSUE THREAD

**Issue by ahcorde** [ros-perception/point_cloud_transport#23]

**Comment by CursedRock17** [comment]
I don't know if I can get to this, but should [the tutorials package](https://github.com/ros-perception/point_cloud_transport_tutorial) be shifted over to a `Tutorials.rst` file within the [doc folder](https://github.com/ros-perception/point_cloud_transport/tree/rolling/point_cloud_transport/doc)? That way everything is more centralized.
