### ISSUE TITLE
Patch to fix build on macos M1

### ISSUE THREAD

**Issue by pfavr2** [ros-perception/point_cloud_transport#56]
I'm maintaining a script for building ros2_rolling on Macos M1.

I had to patch a smartpointer obj.get() to a normal pointer to make it build on Mac:

https://github.com/pfavr2/install_ros2_rolling_on_mac_m1/commit/d1cea75375d0dbf29b68ca29347c0abc7e540949#diff-c5b35afd050d777ba1c8c90761df926bf296d470ffc31b0d3b161e05b1820354

**Comment by ahcorde** [comment]
@pfavr2 I created this PR https://github.com/ros-perception/point_cloud_transport/pull/57, let me know if these changes fix your issues
